---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-4-cust-two
  namespace: cust-two
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 0.25
        memory: 256Mi
      default:
        cpu: 0.5
        memory: 512Mi
