---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-3-cust-two
  namespace: cust-two
spec:
  hard:
    requests.cpu: 1
    requests.memory: 1Gi
    limits.cpu: 2
    limits.memory: 2Gi
    pods: 8
    services: 2
